//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerwisSamochodowy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SerwisDBEntities3 : DbContext
    {
        public SerwisDBEntities3()
            : base("name=SerwisDBEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Czesci> Czesci { get; set; }
        public virtual DbSet<Faktury> Faktury { get; set; }
        public virtual DbSet<Kadra> Kadra { get; set; }
        public virtual DbSet<Klient> Klient { get; set; }
        public virtual DbSet<Naprawy> Naprawy { get; set; }
        public virtual DbSet<Samochody> Samochody { get; set; }
        public virtual DbSet<CzasNaprawy> CzasNaprawy { get; set; }
        public virtual DbSet<LogData> LogData { get; set; }
    }
}
