//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerwisSamochodowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Naprawy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Naprawy()
        {
            this.Czesci = new HashSet<Czesci>();
            this.Faktury = new HashSet<Faktury>();
        }
    
        public int NaprawaID { get; set; }
        public int SamochodID { get; set; }
        public int PracownikID { get; set; }
        public Nullable<decimal> Robocizna { get; set; }
        public Nullable<System.DateTime> GwarancjaDo { get; set; }
        public string OpisUwagi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Czesci> Czesci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faktury> Faktury { get; set; }
        public virtual Kadra Kadra { get; set; }
        public virtual Samochody Samochody { get; set; }
        public virtual CzasNaprawy CzasNaprawy { get; set; }
    }
}
